language: rust
sudo: false

cache: cargo

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    # minimum rustc version
    - rust: 1.20.0
      script: cargo build

script:
  - cargo test
  - 'if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo test --benches; fi'
  - rustdoc --test README.md -L target/debug/deps
  - cargo doc --no-deps

notifications:
  email:
    on_success: never
