[package]
name = "http"
version = "0.1.0"
readme = "README.md"
documentation = ""
repository = ""
homepage = ""
license = "MIT/Apache-2.0"
authors = [
  "Alex Crichton <alex@alexcrichton.com>",
  "Carl Lerche <me@carllerche.com>",
  "Sean McArthur <sean.monstar@gmail.com>",
]
description = """
A set of types for representing HTTP requests and responses.
"""

[dependencies]
bytes = "0.4"

[dev-dependencies]
fnv = "1.0.0"
ordermap = "0.2.9"
seahash = "3.0.5"

[[bench]]
name = "header_map"
path = "benches/header_map/mod.rs"
